package com.bagusxmahendra.mltf.supervisor_agent.dto;

import com.bagusxmahendra.mltf.supervisor_agent.model.KycStatus;
import com.fasterxml.jackson.annotation.JsonAlias;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Map;

/**
 * Structured decision generated by the Google ADK Supervisor Agent.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class SupervisorKycDecision {

    @JsonProperty("decision")
    @JsonAlias({"status", "result", "verdict", "kycStatus", "kyc_status", "decisionStatus"})
    private String decision; // "APPROVED" / "SUCCESS", "IN_REVIEW", "REJECTED" / "FAILED"

    @JsonProperty("decisionConfidence")
    @JsonAlias({"decision_confidence", "confidenceScore", "confidence", "matchScore"})
    private Double decisionConfidence; // 0.0 - 100.0

    @JsonProperty("riskScore")
    @JsonAlias({"risk_score", "score"})
    private Double riskScore; // 0.0 - 100.0

    @JsonProperty("riskLevel")
    @JsonAlias({"risk_level"})
    private String riskLevel; // "LOW", "MEDIUM", "HIGH", "CRITICAL"

    @JsonProperty("explanation")
    @JsonAlias({"explaination", "reasoning", "decisionRationale", "decision_rationale"})
    private String explanation;

    @JsonProperty("remarks")
    private String remarks;

    @JsonProperty("rejectionReason")
    @JsonAlias({"rejection_reason", "rejectReason", "reject_reason"})
    private String rejectionReason;

    @JsonProperty("extractedProfile")
    @JsonAlias({"extracted_profile", "profile", "extractedFields", "verifiedData"})
    private ExtractedProfileData extractedProfile;

    @JsonProperty("documentValidationSummary")
    @JsonAlias({"document_validation_summary", "documentValidation", "docValidation"})
    private Map<String, Object> documentValidationSummary;

    @JsonProperty("selfieValidationSummary")
    @JsonAlias({"selfie_validation_summary", "selfieValidation"})
    private Map<String, Object> selfieValidationSummary;

    @JsonProperty("externalKycSummary")
    @JsonAlias({"external_kyc_summary", "externalKyc"})
    private Map<String, Object> externalKycSummary;

    public SupervisorKycDecision() {
    }

    public KycStatus toKycStatus() {
        if (decision == null || decision.isBlank()) {
            return KycStatus.IN_REVIEW;
        }
        String upper = decision.trim().toUpperCase();
        if ("APPROVED".equals(upper) || "SUCCESS".equals(upper) || "APPROVE".equals(upper) || "PASSED".equals(upper)) {
            return KycStatus.APPROVED;
        }
        if ("REJECTED".equals(upper) || "FAILED".equals(upper) || "REJECT".equals(upper) || "FAIL".equals(upper) || "FRAUD".equals(upper)) {
            return KycStatus.REJECTED;
        }
        if ("IN_REVIEW".equals(upper) || "INREVIEW".equals(upper) || "MANUAL_REVIEW".equals(upper) || "PENDING".equals(upper)) {
            return KycStatus.IN_REVIEW;
        }
        return KycStatus.fromString(upper);
    }

    public String getDecision() {
        return decision;
    }

    public void setDecision(String decision) {
        this.decision = decision;
    }

    public Double getDecisionConfidence() {
        return decisionConfidence;
    }

    public void setDecisionConfidence(Double decisionConfidence) {
        this.decisionConfidence = decisionConfidence;
    }

    public Double getRiskScore() {
        return riskScore;
    }

    public void setRiskScore(Double riskScore) {
        this.riskScore = riskScore;
    }

    public String getRiskLevel() {
        return riskLevel;
    }

    public void setRiskLevel(String riskLevel) {
        this.riskLevel = riskLevel;
    }

    public String getExplanation() {
        return explanation;
    }

    public void setExplanation(String explanation) {
        this.explanation = explanation;
    }

    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public String getRejectionReason() {
        return rejectionReason;
    }

    public void setRejectionReason(String rejectionReason) {
        this.rejectionReason = rejectionReason;
    }

    public ExtractedProfileData getExtractedProfile() {
        return extractedProfile;
    }

    public void setExtractedProfile(ExtractedProfileData extractedProfile) {
        this.extractedProfile = extractedProfile;
    }

    public Map<String, Object> getDocumentValidationSummary() {
        return documentValidationSummary;
    }

    public void setDocumentValidationSummary(Map<String, Object> documentValidationSummary) {
        this.documentValidationSummary = documentValidationSummary;
    }

    public Map<String, Object> getSelfieValidationSummary() {
        return selfieValidationSummary;
    }

    public void setSelfieValidationSummary(Map<String, Object> selfieValidationSummary) {
        this.selfieValidationSummary = selfieValidationSummary;
    }

    public Map<String, Object> getExternalKycSummary() {
        return externalKycSummary;
    }

    public void setExternalKycSummary(Map<String, Object> externalKycSummary) {
        this.externalKycSummary = externalKycSummary;
    }
}
