-- ==============================================================================
-- Google Cloud Spanner Schema Definition: kyc_profile
-- Database: mortgage_db
-- Instance: mltf-spanner
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- 1. Google Standard SQL Dialect (Spanner Default)
-- ------------------------------------------------------------------------------
CREATE TABLE kyc_profile (
    user_id STRING(64) NOT NULL,
    full_name STRING(255) NOT NULL,
    email STRING(255) NOT NULL,
    phone_number STRING(32),
    id_card_number STRING(64),
    id_card_type STRING(32),           -- e.g. NATIONAL_ID, PASSPORT, DRIVERS_LICENSE
    date_of_birth DATE,
    address STRING(500),
    city STRING(100),
    postal_code STRING(20),
    country STRING(100),
    nationality STRING(100),
    occupation STRING(100),
    monthly_income NUMERIC,
    status STRING(32) NOT NULL,         -- PENDING, IN_REVIEW, APPROVED, REJECTED
    risk_score FLOAT64,                 -- e.g. 0.0 to 100.0
    risk_level STRING(32),              -- LOW, MEDIUM, HIGH
    rejection_reason STRING(1000),
    remarks STRING(1000),
    verified_by STRING(64),             -- Supervisor agent / reviewer ID
    verified_at TIMESTAMP OPTIONS (allow_commit_timestamp = true),
    created_at TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp = true),
    updated_at TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp = true)
) PRIMARY KEY (user_id);

-- Migration DDL for existing database instances:
-- ALTER TABLE kyc_profile ALTER COLUMN verified_at SET OPTIONS (allow_commit_timestamp = true);

-- Secondary Indexes for query performance
CREATE INDEX idx_kyc_profile_email ON kyc_profile(email);
CREATE INDEX idx_kyc_profile_status ON kyc_profile(status);
CREATE INDEX idx_kyc_profile_id_card_number ON kyc_profile(id_card_number);

-- ----------------------------------------------------------------------------
-- 2. Application (all loan/facility related data)
-- The transaction_id is the stable key for the complete application journey.
-- ----------------------------------------------------------------------------
CREATE TABLE application (
    transaction_id STRING(64) NOT NULL,
    user_id STRING(64) NOT NULL,
    bank_selection STRING(50),
    application_type STRING(50) NOT NULL,
    status STRING(32) NOT NULL, -- NEW, SUBMITTED, PENDING_APPROVAL, APPROVED, REJECTED
    facility_type STRING(50),
    facility_purpose STRING(100),
    marketing_consent STRING(20),
    application_date DATE,
    created_at TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp = true)
) PRIMARY KEY (transaction_id);

CREATE INDEX idx_application_user_id ON application(user_id);

-- ----------------------------------------------------------------------------
-- 3. Document (documents uploaded for an application)
-- ----------------------------------------------------------------------------
CREATE TABLE document (
    transaction_id STRING(64) NOT NULL,
    document_id STRING(64) NOT NULL,
    document_filename STRING(255),
    gcs_url STRING(2048),
    content_type STRING(100),
    document_status STRING(32),
    document_message STRING(1000),
    document_processing_details STRING(MAX),
    created_at TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp = true)
) PRIMARY KEY (transaction_id, document_id),
  INTERLEAVE IN PARENT application ON DELETE CASCADE;

CREATE INDEX idx_document_transaction_id ON document(transaction_id);

-- ----------------------------------------------------------------------------
-- 4. Applicant (primary/joint applicant and related personal data)
-- Spanner has no AUTO_INCREMENT; applicant_id is generated by the application
-- service when applicant details are added.
-- ----------------------------------------------------------------------------
CREATE TABLE applicant (
    transaction_id STRING(64) NOT NULL,
    applicant_id STRING(64) NOT NULL,
    role STRING(20) NOT NULL,
    full_name STRING(255),
    id_type STRING(50),
    id_no STRING(100),
    nationality STRING(50),
    race STRING(50),
    bumiputera_status BOOL,
    gender STRING(10),
    marital_status STRING(20),
    date_of_birth DATE,
    dependents_count INT64,
    education_level STRING(50),
    mobile_phone STRING(20),
    residential_phone STRING(20),
    email STRING(100),
    perm_address STRING(1000),
    perm_postcode STRING(10),
    perm_city STRING(50),
    perm_state STRING(50),
    mail_address STRING(1000),
    mail_postcode STRING(10),
    employment_status STRING(50),
    employer_name STRING(150),
    nature_of_business STRING(100),
    occupation STRING(100),
    job_position STRING(100),
    length_of_service_years NUMERIC,
    monthly_gross_rm NUMERIC,
    annual_gross_rm NUMERIC,
    emergency_name STRING(255),
    emergency_relationship STRING(50),
    emergency_phone STRING(20),
    spouse_full_name STRING(255),
    spouse_id_no STRING(100),
    spouse_mobile STRING(20),
    spouse_employer STRING(150),
    spouse_monthly_gross_rm NUMERIC
) PRIMARY KEY (transaction_id, applicant_id),
  INTERLEAVE IN PARENT application ON DELETE CASCADE;

-- ----------------------------------------------------------------------------
-- 5. Property (real estate, valuation, and title data)
-- ----------------------------------------------------------------------------
CREATE TABLE property (
    transaction_id STRING(64) NOT NULL,
    property_id STRING(64) NOT NULL,
    property_type STRING(50),
    property_status STRING(50),
    developer_name STRING(150),
    project_name STRING(150),
    contractor_name STRING(150),
    spa_price_rm NUMERIC,
    open_market_rm NUMERIC,
    renovation_value_rm NUMERIC,
    property_address STRING(1000),
    property_postcode STRING(10),
    property_city STRING(50),
    property_state STRING(50),
    title_number STRING(100),
    title_type STRING(50),
    lot_number STRING(50),
    mukim STRING(50),
    district STRING(50),
    is_owner_occupied BOOL,
    is_first_time_buyer BOOL
) PRIMARY KEY (transaction_id, property_id),
  INTERLEAVE IN PARENT application ON DELETE CASCADE;

-- ------------------------------------------------------------------------------
-- Sample Data Insertion (Google Standard SQL)
-- ------------------------------------------------------------------------------
INSERT INTO kyc_profile (
    user_id, full_name, email, phone_number, id_card_number, id_card_type,
    date_of_birth, address, city, postal_code, country, nationality,
    occupation, monthly_income, status, risk_score, risk_level,
    rejection_reason, remarks, verified_by, verified_at, created_at, updated_at
) VALUES (
    'usr_1001', 'John Doe', 'john.doe@example.com', '+1-555-0199', 'ID-987654321', 'NATIONAL_ID',
    DATE '1988-05-12', '123 Main St, Suite 400', 'New York', '10001', 'USA', 'American',
    'Senior Software Engineer', 12500.00, 'APPROVED', 12.5, 'LOW',
    NULL, 'Identity verified successfully via biometric match', 'agent_supervisor_01', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

INSERT INTO kyc_profile (
    user_id, full_name, email, phone_number, id_card_number, id_card_type,
    date_of_birth, address, city, postal_code, country, nationality,
    occupation, monthly_income, status, risk_score, risk_level,
    rejection_reason, remarks, verified_by, verified_at, created_at, updated_at
) VALUES (
    'usr_1002', 'Jane Smith', 'jane.smith@example.com', '+1-555-0245', 'ID-123456789', 'PASSPORT',
    DATE '1992-11-23', '456 Oak Avenue', 'San Francisco', '94102', 'USA', 'American',
    'Financial Analyst', 9500.00, 'IN_REVIEW', 35.0, 'MEDIUM',
    NULL, 'Income documents pending supervisor signoff', NULL, NULL, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

INSERT INTO kyc_profile (
    user_id, full_name, email, phone_number, id_card_number, id_card_type,
    date_of_birth, address, city, postal_code, country, nationality,
    occupation, monthly_income, status, risk_score, risk_level,
    rejection_reason, remarks, verified_by, verified_at, created_at, updated_at
) VALUES (
    'usr_1003', 'Robert Johnson', 'robert.j@example.com', '+1-555-0378', 'ID-556677889', 'NATIONAL_ID',
    DATE '1985-02-18', '789 Pine Road', 'Chicago', '60601', 'USA', 'American',
    'Consultant', 6000.00, 'REJECTED', 85.0, 'HIGH',
    'Unverified identity documents and high credit risk', 'Documentation expired', 'agent_supervisor_02', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
);

-- ------------------------------------------------------------------------------
-- 2. Alternative PostgreSQL Dialect (if Spanner database uses PostgreSQL dialect)
-- ------------------------------------------------------------------------------
/*
CREATE TABLE kyc_profile (
    user_id VARCHAR(64) NOT NULL PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone_number VARCHAR(32),
    id_card_number VARCHAR(64),
    id_card_type VARCHAR(32),
    date_of_birth DATE,
    address VARCHAR(500),
    city VARCHAR(100),
    postal_code VARCHAR(20),
    country VARCHAR(100),
    nationality VARCHAR(100),
    occupation VARCHAR(100),
    monthly_income NUMERIC,
    status VARCHAR(32) NOT NULL,
    risk_score DOUBLE PRECISION,
    risk_level VARCHAR(32),
    rejection_reason VARCHAR(1000),
    remarks VARCHAR(1000),
    verified_by VARCHAR(64),
    verified_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_kyc_profile_email ON kyc_profile(email);
CREATE INDEX idx_kyc_profile_status ON kyc_profile(status);
CREATE INDEX idx_kyc_profile_id_card_number ON kyc_profile(id_card_number);
*/
